# Site settings
# in the templates available like {{ site.myvariable }}.
title: Handgemachte Akustiknummern aus Innsbruck
email: dreizimmer@gmail.com
brand: Dreizimmerwohnung
headline:
description: > # this means to ignore newlines until "baseurl:"
  Handgemachte Akustiknummern aus Innsbruck
baseurl: "" # the subpath of your site, e.g. /blog
url:
copyright: Dreizimmerwohnung

# Build settings
markdown: kramdown

# Account ids
snapwidget:

# Contacts
email: dreizimmer@notyetanemail.at

# Tracking
googleAnalitycsID:
